lang = "TS"
organization_id = "ginger-society"
dir = "src/services"
refs_file = "src/shared/references.ts"
service_type = "Portal"

[services."@ginger-society/IAMService"]
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"
prod = "https://api.gingersociety.org/iam"
prod_k8 = "http://iam-service-api-service/iam"
dev = "http://localhost:8080/iam"

[services."@ginger-society/IAMAdminService"]
prod = "https://api.gingersociety.org/iam-admin"
prod_k8 = "http://iam-service-api-service/iam-admin"
stage = "https://api-staging.gingersociety.org/iam-admin"
dev = "http://localhost:8080/iam-admin"
stage_k8 = "http://iam-service-api-service/iam-admin"

[portals_refs."@ginger-society/iam-frontend-users"]
stage = "https://iam-staging.gingersociety.org"
dev = "http://localhost:3001"
prod = "https://iam.gingersociety.org"

[ws_refs."@ginger-society/IAMAdminService"]
stage = ""
prod_k8 = ""
prod = ""
dev = ""
stage_k8 = ""

[ws_refs."@ginger-society/IAMService"]
prod_k8 = ""
prod = ""
stage_k8 = ""
stage = ""
dev = ""

[urls]
stage = "https://iam-admin-staging.gingersociety.org"
dev = "http://localhost:3003"

[urls_ws]
