allow_registration = true 
dir = "src/services" 
disabled = true 
friendly_name = "IAM Admin portal" 
lang = "TS" 
organization_id = "ginger-society" 
refs_file = "src/shared/references.ts" 
service_type = "Portal" 
sso_redirect_suffix = "/#/handle-auth/" 
tnc_link = "https://gingersociety.org/terms-of-use" # if allow registration is true , then we should provide the tnc link

[services."@ginger-society/IAMService"]
dev = "http://localhost:8080/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs."@ginger-society/iam-frontend-users"]
dev = "http://localhost:3001"
stage = "https://iam-staging.gingersociety.org"

[ws_refs]

[urls]
dev = "http://localhost:3003"
stage = "https://iam-admin-staging.gingersociety.org"

[urls_ws]
